spring: 
  application:
    name: kayak-zuul
server:
  port: 8400
zuul: 
  ignoredServices: '*' #忽略所有未配置的service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    connection-request-timeout-millis: 20000
  routes:
    aliyun: #自定义名称
      path: /aliyun/**
      service-id: kayak-aliyun #/aliyun/开头的路径转发至kayak-aliyun微服务
    k8s:
      path: /k8s/**
      service-id: kayak-kubernetes
    system:
      path: /feigen/**
      service-id: kayak-feigen
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/